#!/bin/bash

git pull; cd pickel; git pull; cd ..; cd slowhand; git pull; cd ..;

docker compose exec web composer -d site/ update
docker compose exec web composer -d slowhand/backend update
docker compose exec web slowhand/backend/bin/slowhand setup

curl -vv http://localhost:9902/auth/create_user -H 'x-slowhand-admin-secret: 123456' \
     -H 'Content-type: application/json' \
     --data '{"email":"test@20sec.net","password":"xyz123456","name":"test"}'
