#!/bin/bash

docker compose exec web composer -d site/ update
docker compose exec web composer -d slowhand/backend update
docker compose exec web slowhand/backend/bin/slowhand setup

curl -vv http://localhost:9902/auth/register -H 'x-slowhand-admin-secret: 123456' \
     -H 'Content-type: application/json' \
     --data '{"email":"sh-start@20sec.net","password":"xyz123456","name":"rw", "password_confirmation":"xyz123456"}'
